Add fix for tokens
EvgeniaKosorotova/API_service_RabbitMQ pull request #9
Opened 2020-04-10 15:01 UTC by EvgeniaKosorotova

2020-04-15 07:00 UTC, edubovskiy requested changes

2020-04-15 07:00 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/TokensController.cs
> +            if (await _tokenManager.AddTokenAsync(user, refreshToken) > 0)
It is not clear why method to creates token returns count and why it compared with 0. Is it creates multiple tokens?

2020-04-15 07:00 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/TokensController.cs
> +                        LifeTime = TimeSpan.ParseExact(_configuration.GetSection("Settings:JWT:AccessToken:Expiry").Value, "c", null),
Can't it be changed to code like `LifeTime = Configuration.GetValue<TimeSpan>("...");` ?

2020-04-15 07:00 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/TokensController.cs
> +            if (userId <= 0)
Don't compare ids with `<` or using 0. If wasn't found in token (just for example) then it should return null (return type should be int?).

2020-04-15 07:00 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/TokensController.cs
> +                && await _tokenManager.AddTokenAsync(user, newRefreshToken) > 0)
Why there continuous checks with 0? what means this condition?

2020-04-15 07:00 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/UsersController.cs
>              UserModel user = _userManager.GetAsync(username: authData.Username).GetAwaiter().GetResult();
GetAwaiter() and GetResult() are not needed in method with "async". Please read how async methods are working in asp.net framework and what purpose of such methods.

2020-04-15 07:00 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/UsersController.cs
> +            if (!(user != null && user.Username == authData.Username && user.Password == _helper.GetHash(authData.Password)))
Additional check by username is not needed because your method already returns user by username. Probably condition too complex. Why we can't check just:
```
if (user == null)
{
   ...some code to create user...

   return success_result;
}

return error;

2020-04-15 07:00 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/UsersController.cs
> +        public async Task<IActionResult> DeleteAsync([FromQuery]int id)
Why you decided to place id value in query string?

2020-04-15 07:00 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/UsersController.cs
> +                        new
1. Earlier we discussed that anonymous objections sholdn't be used. Why them still used in test task?
2. It is not needed to return message that object was created. You could return just 204 in this case.

2020-04-15 07:00 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Logic/Helper.cs
> +    public class Helper
What purpose of this helper? Why such name was selected for class.

2020-05-03 15:11 UTC, edubovskiy requested changes

2020-05-03 15:11 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/TokensController.cs
> +            var userId = await _tokenManager.GetUser(token: refreshToken);
User object can be retrieved in first request to prevent need to make 2 requests to database (performance).

2020-05-03 15:11 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/TokensController.cs
> +                && await _tokenManager.AddTokenAsync(user, newRefreshToken))
Ideally (if we have separate business layer) controler should have only code to validate **format** if input data, call some method to process request and build response. Criteria here: in case if project will be moved to other framework then you shouldn't rework logic of endpoint, only code to read request and build response.

In this regard, all logic how to process request and data in storage should be moved to method ot service/manager class. So, it is better to move lines 88-93 to some manager class if possible.

2020-05-03 15:11 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/UsersController.cs
>                      return Created(string.Empty,
POST method must return id or object of created entity.

2020-05-03 15:11 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Logic/TokenManager.cs
> +            return await db.SaveChangesAsync() > 0 ? true: false;
1) Please simplify condition: `return await db.SaveChangesAsync() > 0;`.
2) Not critical: It is not required to return some boolean value in this case because if something will happen during saving then it will cause exception.

2020-05-03 15:11 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Logic/TokenManager.cs
> +        public async Task<int?> GetUser(string token = "")
1) Why default value is needed here?
2) Use `string.Empty` instead of `""`. It is more clear and C# compiler anyway will replace all `""` with `string.Empty` during compilation.

2020-05-03 15:11 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Logic/UserManager.cs
> +        public async Task<UserModel> GetAsync(int? id = null, string username = null, string password = null)
There no need to mix multiple optional parameters in one method. It causes redundant code and conditions. Make just separate methods to get by id and by creds.

2020-05-03 15:11 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Models/DataContext.cs
> +                entity.Property(e => e.Id).HasColumnName("id");
Why you change column names in db to use lowercase? No objections if you prefer this way, it just unusual convention for mssql :)

2020-05-03 15:11 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Models/DataContext.cs
> +                    .HasColumnName("refreshToken");
Set max length for all string values in db. It could improve performance and disk usage.

2020-05-03 15:11 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Models/TokenModel.cs
> +        public virtual UserModel IdUserNavigation { get; set; }
Name just User to simplify because it will reference user entity.

2020-05-06 16:40 UTC, EvgeniaKosorotova commented on QueueMessageSender/QueueMessageSender/Logic/TokenManager.cs
> +        public async Task<int?> GetUser(string token = "")
Each optional parameter has a default value as part of its definition. If no argument is sent for that parameter, the default value is used. Default values must be constants.

2020-05-11 05:42 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Logic/TokenManager.cs
> +        public async Task<int?> GetUser(string token = "")
Why token should be optional? Without token you will not be able to return userId in this case.

2020-05-13 06:05 UTC, edubovskiy approved these changes
Everything looks fine except few minor inline notes.

2020-05-13 06:05 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Controllers/UsersController.cs
> +    [EnableCors("CorsPolicy")]
If cors needed in all controllers then it could be enabled globally. Attribute should be used only in case if it is needed for part of controllers.

2020-05-13 06:05 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Models/DataContext.cs
> +        //        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
Unneeded comments.

2020-05-13 06:05 UTC, edubovskiy commented on QueueMessageSender/QueueMessageSender/Models/UserModel.cs
> +            Tokens = new HashSet<TokenModel>();
Why this is needed? Navigation properties initialized by framework out of the box.

2020-05-17 18:22 UTC, merged